### ISSUE TITLE
error: package id.kakzaki.blue_thermal_printer does not exist

### ISSUE THREAD

**Issue by 10urbulut** [kakzaki/blue_thermal_printer#134]
Hello, i had a problem. I wrote flutter and then redirect me to  blue_thermal_printer 
[check this](https://github.com/flutter/flutter/issues/99287#issuecomment-1056237497)

**Comment by YahalomsGuy** [comment]
if you are trying to run the example app, you must download the all package, since the example app relies on the base package, where the example app is in.

Or you could just import the package as you would with a regular package from pub.dev, but then you may need to delete the dependency in pubspec.yaml of the example app.
