### ISSUE TITLE
Sinhala font doesn't support. What iso number?

### ISSUE THREAD

**Issue by sajiyabro98** [kakzaki/blue_thermal_printer#142]
'බැඳපු මිරිස් කුඩු'

I'm try to these

charset: "iso-8859" 
charset: "iso8859" 
charset: "ISO-8859" 

But does'nt working!!!
How to solve my problem 
It urgent... please

**Comment by anushkapubudu** [comment]
No way, I'm still trying to print සිංහල. Some printers not support sinhala. I think better, you can mention printer version here. And I found a solution to print characters as images, 
https://stackoverflow.com/a/70845029/12300603
but I know it is not the best solution. When printing as images, printer taking too time. So you find any solution to this. Please let me know because I too struck to this problem. Thanks in advance

**Comment by sajiyabro98** [comment]
@anushkapubudu thanks for reply..  customer said that I have printed Sinhala from the printer.. 
[https://github.com/kakzaki/blue_thermal_printer/issues/82#issuecomment-1048964685](url)
this is similar as you solution but i try to find iso version
again thank you

**Comment by anushkapubudu** [comment]
@sajiyabro98 if you found any solution, please share with me. Thanks

**Comment by sajiyabro98** [comment]
@anushkapubudu noway find this. can you share your code... please
