### ISSUE TITLE
 Some lines failed to print.

### ISSUE THREAD

**Issue by gabrielrodrigodesbesell** [kakzaki/blue_thermal_printer#20]
I am having a (not always) printing problem, sometimes the printing is perfect and sometimes it does not print a few lines or an image for example. Is anyone going through this?

**Comment by kakzaki** [comment]
@gabrielrodrigodesbesell are you using image under 300px x300px ?

**Comment by gabrielrodrigodesbesell** [comment]
@kakzaki I am not using images with resolutions greater than 300px. I have a 300px X 171px image, another 250px X 85px and a QRCode generated by the library itself. In addition to the images I have 22 more line of words.

**Comment by gabrielrodrigodesbesell** [comment]
See printing examples. The only one that printed correctly was the one that is circled in red:

![CCI28102019_00001](https://user-images.githubusercontent.com/6655304/67685222-70c49f00-f973-11e9-8531-98c1e25b0464.jpg)

**Comment by gabrielrodrigodesbesell** [comment]
Images used in print:

![logo](https://user-images.githubusercontent.com/6655304/67685343-a9647880-f973-11e9-9cea-dd37e3d06672.png)
![naopago](https://user-images.githubusercontent.com/6655304/67685347-ab2e3c00-f973-11e9-9430-6e1c0cb1fd24.png)

**Comment by gabrielrodrigodesbesell** [comment]
Any suggestion?

**Comment by FernandoUFS** [comment]
Maybe the problem is your printer buffer size. I suggest you wait some time after print each image, and wait after each 10 lines of text. Also print using await.

E.g.:
await bluetooth.printImage(pathImage);
await new Future.delayed(new Duration(milliseconds: 500));
await bluetooth.printCustom(sometext,0,0);
await bluetooth.printCustom(sometext,0,0);
await bluetooth.printCustom(sometext,0,0);
await bluetooth.printCustom(sometext,0,0);
await bluetooth.printCustom(sometext,0,0);
await bluetooth.printCustom(sometext,0,0);
await bluetooth.printCustom(sometext,0,0);

**Comment by gabrielrodrigodesbesell** [comment]
@FernandoUFS perfect, solved. Only the increase in time takes one second.
Tku
