### ISSUE TITLE
Is there a way to print SVG images?

### ISSUE THREAD

**Issue by luissouza** [kakzaki/blue_thermal_printer#38]
Is there a way to print SVG images?
I not have success trying with SVG.

**Comment by 792266344** [comment]
> Is there a way to print SVG images?
> I not have success trying with SVG.

I don't know what do you want to print
A few days ago, I want to print barcode,but i find that the plugin only can print PNG its seems
I try to convert SVG to PNG ,i failed
Finally,I print barcode success with change its code,because there is a method named 'pringQRcode'
So I create a new Method to print barcode,the plugin use 'com.google.zxing.barcodeformat' to print
if you wang to print barcode ,you can try it

**Comment by luissouza** [comment]
@792266344 , yes, i want to print barcode too, i try to convert SVG to PNG and i failed too.. you can please send me the piece of code that you are doing this? Im trying this for 15 days.. thank you so much!

**Comment by 792266344** [comment]
> @792266344 , yes, i want to print barcode too, i try to convert SVG to PNG and i failed too.. you can please send me the piece of code that you are doing this? Im trying this for 15 days.. thank you so much!

view the java file ('android/src/main/java/id/kakzaki/blue_thermal_printer/BlueThermalPrinterPlugin.java') about this plugin ,you can find that it have a method named 'printQRcode' in this file 
In this file ,line 581,it use 'BarcodeFormat.QR_CODE' to print QRCode
The BarcodeFormat is a enum data ,so i guesses it have a value name 'CODE_128'
In fact, it is true ,so ,you can copy the 'printQRcode' method ,then parse the code,
change 'BarcodeFormat.QR_CODE' to 'BarcodeFormat.CODE_128' and save the new method use a new name
BUT,The defect is you must to download the plugin Not inject it
Because you need to change it's code
Finally ,you can use the new method like 'printQRcode'

**Comment by abbas-25** [comment]
> > @792266344 , yes, i want to print barcode too, i try to convert SVG to PNG and i failed too.. you can please send me the piece of code that you are doing this? Im trying this for 15 days.. thank you so much!
> 
> view the java file ('android/src/main/java/id/kakzaki/blue_thermal_printer/BlueThermalPrinterPlugin.java') about this plugin ,you can find that it have a method named 'printQRcode' in this file
> In this file ,line 581,it use 'BarcodeFormat.QR_CODE' to print QRCode
> The BarcodeFormat is a enum data ,so i guesses it have a value name 'CODE_128'
> In fact, it is true ,so ,you can copy the 'printQRcode' method ,then parse the code,
> change 'BarcodeFormat.QR_CODE' to 'BarcodeFormat.CODE_128' and save the new method use a new name
> BUT,The defect is you must to download the plugin Not inject it
> Because you need to change it's code
> Finally ,you can use the new method like 'printQRcode'

Hi, I am in a similar situation. What do you mean by downloading the plugin?

I changed the code from BarcodeFormat.QR_CODE to BarcodeFormat.CODE_128.
Did flutter clean, then flutter run.

Client is testing on my code because I don't have the printer so I can't tell you the result until I get a response from him.

Thankss!!
